# Travis CI 설정 파일 (.travis.yml)

language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
# gradle을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여,
# 같은 의존성은 다음 배포부터 다시 받지 않도록 설정
cache:
  directories:
    - '$Home/.m2/repository'
    - '$Home/.gradle'

script: "./gradlew clean build"

# before_deploy는 deploy 명령어가 실행되기 전에 수행됩니다.
# CodeDeploy는 Jar 파일을 인식하지 못하기 때문에 Jar + 기타 설정 파일들을 모아 압축합니다.
before_deploy:
  # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  # before-deploy로 이동 후 전체 압축
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/ys-springboot-webservice.zip

# deploy에서는 외부 서비스와 연동될 행위들을 선업합니다.
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ys-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ys-springboot-build
    key: ys-springboot-webservice.zip
    bundle_type: zip
    application: ys-springboot-webservice # CodeDeploy Application Name
    deployment_group: ys-springboot-webservice-group # CodeDeploy Deployment Group Name
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - young4127s@naver.com